apiVersion: v1
kind: Service
metadata:
  name: cloudlet-backend
  namespace: {{ include "cloudlet-manager.namespace" . }}
  labels:
    {{- include "cloudlet-manager.backendLabels" . | nindent 4 }}
spec:
  selector:
    {{- include "cloudlet-manager.selectorBackend" . | nindent 4 }}
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
