{{- if and .Values.sso.enabled .Values.vault.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudlet-sso-secret
  namespace: {{ include "cloudlet-manager.namespace" . }}
  labels:
    {{- include "cloudlet-manager.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.vault.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.vault.secretStoreName }}
    kind: {{ .Values.vault.secretStoreKind }}
  target:
    name: cloudlet-sso-secret
    creationPolicy: Owner
  data:
    - secretKey: client-secret
      remoteRef:
        key: {{ .Values.vault.paths.ssoClientSecret }}
        property: client-secret
{{- end }}
