{{- if .Values.vault.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudlet-git-token
  namespace: {{ include "cloudlet-manager.namespace" . }}
  labels:
    {{- include "cloudlet-manager.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.vault.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.vault.secretStoreName }}
    kind: {{ .Values.vault.secretStoreKind }}
  target:
    name: cloudlet-git-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: {{ .Values.vault.paths.gitToken }}
        property: token
{{- end }}
