{{- if and .Values.sso.enabled .Values.vault.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudlet-oauth-proxy-secret
  namespace: {{ include "cloudlet-manager.namespace" . }}
  labels:
    {{- include "cloudlet-manager.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.vault.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.vault.secretStoreName }}
    kind: {{ .Values.vault.secretStoreKind }}
  target:
    name: cloudlet-oauth-proxy-secret
    creationPolicy: Owner
  data:
    - secretKey: cookie-secret
      remoteRef:
        key: {{ .Values.vault.paths.oauthCookieSecret }}
        property: cookie-secret
{{- end }}
