apiVersion: v1
kind: Secret
metadata:
  name: cloudlet-manager-config
  namespace: cloudlet-manager
type: Opaque
stringData:
  CLOUDLET_GITHUB_TOKEN: "REPLACE_ME"
  CLOUDLET_GITHUB_SPEC_REPO: "dbirenfe/cloudlets-spec"
  CLOUDLET_GITHUB_SPEC_BRANCH: "main"
  CLOUDLET_KEYCLOAK_URL: ""
  CLOUDLET_KEYCLOAK_REALM: ""
  CLOUDLET_KEYCLOAK_CLIENT_ID: ""
  CLOUDLET_KEYCLOAK_CLIENT_SECRET: ""
  CLOUDLET_ALLOWED_GROUPS: "[]"
  CLOUDLET_CORS_ORIGINS: '["*"]'
